# Generated by Django 3.2 on 2021-05-22 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='reserved_from',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='reserved_to',
            field=models.DateField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='BookedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_from', models.DateField(default=None, null=True)),
                ('reserved_to', models.DateField(default=None, null=True)),
                ('apartment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booked_apartment', to='listings.listing')),
                ('hotel_room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booked_hotel_room', to='listings.hotelroom')),
                ('reserved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
